### ISSUE TITLE
Gifs should be responsive

### ISSUE THREAD

**Issue by johnson-rl** [mblair415/wheresMyHero#11]

**Comment by mblair415** [comment]
It works now.  To be clear: 
https://v4-alpha.getbootstrap.com/content/images/

The contents there are garbage.  Including the class "img-responsive" makes the gif's responsive.  I think I spent about 4 hours trying different ways to follow the bootstrap documentation.  Looked at a couple youtube videos that all said the same (different) thing.  Youtube was right.  Bootstrap documentation was wrong.  Michael is bitter.
